[[constraint]]
  name = "go.uber.org/zap"
  version = "~1.9.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "~1.2.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.17.0"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  revision = "51d6538a90f86fe93ac480b35f37b2be17fef232"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "~3.1.2"

[[constraint]]
  name = "github.com/rubenv/sql-migrate"
  revision = "5a8808c14925f69d2228981db113f672ad047e69"

[[constraint]]
  name = "github.com/lib/pq"
  revision = "9eb73efc1fcc404148b56765b0d3f61d9a5ef8ee"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "~1.6.2"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "~3.2.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  revision = "95ba29eb981bbb27d92e1f70bf8a1949452d926b"

[[constraint]]
  name = "github.com/yuin/gopher-lua"
  revision = "db9ae37725ec65ae634769088627d2d118faf06a"

[[constraint]]
  name = "github.com/gorhill/cronexpr"
  revision = "88b0669f7d75f171bd612b874e52b95c190218df"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "505ab145d0a99da450461ae2c1a9f6cd10d1f447"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "~1.21.9"

[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "bcbbc08eb2ddff3af83bbf11e7ec13b4fd730b6e"

[[constraint]]
  name = "go.opencensus.io"
  version = "~0.14.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.2"

[[constraint]]
  name = "github.com/cockroachdb/cockroach-go"
  revision = "59c0560478b705bf9bd12f9252224a0fad7c87df"

[[constraint]]
  name = "github.com/blevesearch/bleve"
  revision = "5cf4e4e02e8a1aec8df8c6773d08e364ee694cea"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"
